/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "dff-variants.v:99" *)
module dff_design(sd, sen, srst, clk, q, qe, qer, qesr);
  (* src = "dff-variants.v:100" *)
  input clk;
  (* src = "dff-variants.v:101" *)
  output q;
  (* src = "dff-variants.v:101" *)
  output qe;
  (* src = "dff-variants.v:101" *)
  output qer;
  (* src = "dff-variants.v:101" *)
  output qesr;
  (* src = "dff-variants.v:100" *)
  input sd;
  (* src = "dff-variants.v:100" *)
  input sen;
  (* src = "dff-variants.v:100" *)
  input srst;
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000101000001100)
  ) _0_ (
    .I0(sd),
    .I1(qer),
    .I2(srst),
    .I3(sen),
    .O(qer)
  );
  (* src = "dff-variants.v:41|/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFESR _1_ (
    .C(clk),
    .D(sd),
    .E(sen),
    .Q(qesr),
    .R(srst)
  );
  (* src = "dff-variants.v:8|/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _2_ (
    .C(clk),
    .D(sd),
    .Q(q)
  );
  (* src = "dff-variants.v:17|/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _3_ (
    .C(clk),
    .D(sd),
    .E(sen),
    .Q(qe)
  );
endmodule
