

# Common setups for all Makefiles like variables for target directories:
include ../../ETC/setup.mk

# Specific, local Makefile:
include MakefileComp

# Use the template for for leafe directories:
include $(MkBase)/LeafTemplate.mk

