

# Common setups for all Makefiles like variables for target directories:
include ../../ETC/setup.mk

# Set chapter:
chapter := 10-Communication

# Use the template for for leafe directories:
include $(MkBase)/LeafTemplate.mk

# Specific, local Makefile:
include MakefileComp


