#!/bin/sh
#
# Script to generate the summary report based on the synthesis results
# obtained by the script script-RegFile.sh


summaryf=ReportSummary.txt

echo "" > $summaryf

echo " "
echo "=================================================================== "| tee -a $summaryf
echo "=================================================================== "| tee -a $summaryf
echo "  Summary "| tee -a $summaryf
echo "=================================================================== "| tee -a $summaryf

for genbasf in  RegisterFile-wBRAM RegisterFile-noBRAM
do
    echo "=================================================================== " | tee -a $summaryf

    echo "   $genbasf  " | tee -a $summaryf
    echo "   Delay   Logic levels      Logic Cells     BRAMs       I/O   " \
	| tee -a $summaryf
    echo "---------------------------------------------------------------" \
	| tee -a $summaryf

    # The header for the latex table file:
    latexf=$genbasf-summarytable.tex;
    echo "% "  >$latexf
    echo "% $latexf generated by $0 " >>$latexf
    echo "% "  >>$latexf
    echo "\\\\begin{tabular}{rc|rr|rr|rr}" >>$latexf
    echo " Delay (ns) & Logic Levels & \multicolumn{2}{c|}{Logic Cells} & \multicolumn{2}{c|}{BRAMs} & \multicolumn{2}{c}{I/O} \\\\\\\\" >>$latexf
    echo "\hline" >>$latexf
    
    tirf=$genbasf*tir
    rerf=$genbasf*rer

    # We do the same reporting twice, once as plain text and once as latex code:
    # The plain text outpput on the terminal and in a file:
    awk '/Total number of logic levels/ { nrll = $6; }
     	 /Total path delay/ { pathdelay=$4; }
	 END {printf " %5.1f ns     %3d ", pathdelay, nrll;}'\
		$tirf  | tee -a $summaryf
    awk '/Info:[ \t]*ICESTORM_LC:/ { nrlc=$3; sub("/","", nrlc); prlc=$5; sub("%","", prlc);}
         /Info:[ \t]*SB_IO:/ { nrio=$3; sub("/","", nrio); prio=$5; sub("%","", prio); }
         /Info:[ \t]*ICESTORM_RAM:/ { nrbram=$3; sub("/","", nrbram); prbram=$5; sub("%","", prbram);  }
         END {printf "         %4d (%3d%%)   %2d (%3d%%)   %5d (%3d%%)\n", nrlc, prlc, nrbram, prbram, nrio, prio;}' $rerf  | tee -a $summaryf

    # The latex file:
    awk '/Total number of logic levels/ { nrll = $6; }
         /Total path delay/ { pathdelay=$4; }
	 END {printf "  %5.1f &    %3d ", pathdelay, nrll;}'\
		$tirf  >> $latexf
    awk '/Info:[ \t]*ICESTORM_LC:/ { nrlc=$3; sub("/","", nrlc); prlc=$5; sub("%","", prlc);}
         /Info:[ \t]*SB_IO:/ { nrio=$3; sub("/","", nrio); prio=$5; sub("%","", prio); }
         /Info:[ \t]*ICESTORM_RAM:/ { nrbram=$3; sub("/","", nrbram); prbram=$5; sub("%","", prbram); }
         END {printf " &  %4d & (%3d\\%%)  & %2d & (%3d\\%%) & %5d & (%3d\\%%)\\\\ \n", nrlc, prlc, nrbram, prbram, nrio, prio;}' $rerf  \
		 >> $latexf
    echo "\\\\end{tabular}" >>$latexf

done

echo " "
echo "Report written to $summaryf and as latex code to tex files."
