/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "RegisterFile.v:5" *)
module RegisterFile(clk, wrEn, wrAddr, wrData, rdAddrA, rdDataA);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  (* src = "RegisterFile.v:9" *)
  input clk;
  (* src = "RegisterFile.v:13" *)
  input [3:0] rdAddrA;
  (* src = "RegisterFile.v:14" *)
  output [15:0] rdDataA;
  wire [15:0] \regfile[0] ;
  wire [15:0] \regfile[10] ;
  wire [15:0] \regfile[11] ;
  wire [15:0] \regfile[12] ;
  wire [15:0] \regfile[13] ;
  wire [15:0] \regfile[14] ;
  wire [15:0] \regfile[15] ;
  wire [15:0] \regfile[1] ;
  wire [15:0] \regfile[2] ;
  wire [15:0] \regfile[3] ;
  wire [15:0] \regfile[4] ;
  wire [15:0] \regfile[5] ;
  wire [15:0] \regfile[6] ;
  wire [15:0] \regfile[7] ;
  wire [15:0] \regfile[8] ;
  wire [15:0] \regfile[9] ;
  (* src = "RegisterFile.v:11" *)
  input [3:0] wrAddr;
  (* src = "RegisterFile.v:12" *)
  input [15:0] wrData;
  (* src = "RegisterFile.v:10" *)
  input wrEn;
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _228_ (
    .I0(_008_),
    .I1(_014_),
    .I2(rdAddrA[1]),
    .I3(1'b0),
    .O(_006_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _229_ (
    .I0(_013_),
    .I1(_012_),
    .I2(_009_),
    .I3(rdAddrA[3]),
    .O(_008_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _230_ (
    .I0(_010_),
    .I1(_011_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_009_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _231_ (
    .I0(\regfile[7] [0]),
    .I1(\regfile[3] [0]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_010_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _232_ (
    .I0(\regfile[6] [0]),
    .I1(\regfile[2] [0]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_011_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _233_ (
    .I0(\regfile[14] [0]),
    .I1(\regfile[10] [0]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_012_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _234_ (
    .I0(\regfile[15] [0]),
    .I1(\regfile[11] [0]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_013_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _235_ (
    .I0(_019_),
    .I1(_018_),
    .I2(_015_),
    .I3(rdAddrA[3]),
    .O(_014_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _236_ (
    .I0(_016_),
    .I1(_017_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_015_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _237_ (
    .I0(\regfile[5] [0]),
    .I1(\regfile[1] [0]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_016_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _238_ (
    .I0(\regfile[4] [0]),
    .I1(\regfile[0] [0]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_017_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _239_ (
    .I0(\regfile[12] [0]),
    .I1(\regfile[8] [0]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_018_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _240_ (
    .I0(\regfile[13] [0]),
    .I1(\regfile[9] [0]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_019_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _241_ (
    .I0(_020_),
    .I1(_026_),
    .I2(rdAddrA[1]),
    .I3(1'b0),
    .O(_226_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _242_ (
    .I0(_025_),
    .I1(_024_),
    .I2(_021_),
    .I3(rdAddrA[3]),
    .O(_020_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _243_ (
    .I0(_022_),
    .I1(_023_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_021_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _244_ (
    .I0(\regfile[7] [1]),
    .I1(\regfile[3] [1]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_022_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _245_ (
    .I0(\regfile[6] [1]),
    .I1(\regfile[2] [1]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_023_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _246_ (
    .I0(\regfile[14] [1]),
    .I1(\regfile[10] [1]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_024_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _247_ (
    .I0(\regfile[15] [1]),
    .I1(\regfile[11] [1]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_025_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _248_ (
    .I0(_031_),
    .I1(_030_),
    .I2(_027_),
    .I3(rdAddrA[3]),
    .O(_026_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _249_ (
    .I0(_028_),
    .I1(_029_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_027_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _250_ (
    .I0(\regfile[5] [1]),
    .I1(\regfile[1] [1]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_028_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _251_ (
    .I0(\regfile[4] [1]),
    .I1(\regfile[0] [1]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_029_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _252_ (
    .I0(\regfile[12] [1]),
    .I1(\regfile[8] [1]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_030_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _253_ (
    .I0(\regfile[13] [1]),
    .I1(\regfile[9] [1]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_031_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _254_ (
    .I0(_032_),
    .I1(_039_),
    .I2(rdAddrA[1]),
    .I3(1'b0),
    .O(_227_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _255_ (
    .I0(_038_),
    .I1(_037_),
    .I2(_033_),
    .I3(rdAddrA[3]),
    .O(_032_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _256_ (
    .I0(_034_),
    .I1(_035_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_033_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _257_ (
    .I0(\regfile[7] [2]),
    .I1(\regfile[3] [2]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_034_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _258_ (
    .I0(\regfile[6] [2]),
    .I1(\regfile[2] [2]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_035_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _259_ (
    .I0(\regfile[14] [2]),
    .I1(\regfile[10] [2]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_037_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _260_ (
    .I0(\regfile[15] [2]),
    .I1(\regfile[11] [2]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_038_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _261_ (
    .I0(_044_),
    .I1(_043_),
    .I2(_040_),
    .I3(rdAddrA[3]),
    .O(_039_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _262_ (
    .I0(_041_),
    .I1(_042_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_040_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _263_ (
    .I0(\regfile[5] [2]),
    .I1(\regfile[1] [2]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_041_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _264_ (
    .I0(\regfile[4] [2]),
    .I1(\regfile[0] [2]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_042_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _265_ (
    .I0(\regfile[12] [2]),
    .I1(\regfile[8] [2]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_043_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _266_ (
    .I0(\regfile[13] [2]),
    .I1(\regfile[9] [2]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_044_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _267_ (
    .I0(_045_),
    .I1(_051_),
    .I2(rdAddrA[1]),
    .I3(1'b0),
    .O(_000_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _268_ (
    .I0(_050_),
    .I1(_049_),
    .I2(_046_),
    .I3(rdAddrA[3]),
    .O(_045_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _269_ (
    .I0(_047_),
    .I1(_048_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_046_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _270_ (
    .I0(\regfile[7] [3]),
    .I1(\regfile[3] [3]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_047_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _271_ (
    .I0(\regfile[6] [3]),
    .I1(\regfile[2] [3]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_048_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _272_ (
    .I0(\regfile[14] [3]),
    .I1(\regfile[10] [3]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_049_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _273_ (
    .I0(\regfile[15] [3]),
    .I1(\regfile[11] [3]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_050_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _274_ (
    .I0(_056_),
    .I1(_055_),
    .I2(_052_),
    .I3(rdAddrA[3]),
    .O(_051_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _275_ (
    .I0(_053_),
    .I1(_054_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_052_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _276_ (
    .I0(\regfile[5] [3]),
    .I1(\regfile[1] [3]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_053_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _277_ (
    .I0(\regfile[4] [3]),
    .I1(\regfile[0] [3]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_054_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _278_ (
    .I0(\regfile[12] [3]),
    .I1(\regfile[8] [3]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_055_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _279_ (
    .I0(\regfile[13] [3]),
    .I1(\regfile[9] [3]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_056_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _280_ (
    .I0(_057_),
    .I1(_063_),
    .I2(rdAddrA[1]),
    .I3(1'b0),
    .O(_001_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _281_ (
    .I0(_062_),
    .I1(_061_),
    .I2(_058_),
    .I3(rdAddrA[3]),
    .O(_057_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _282_ (
    .I0(_059_),
    .I1(_060_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_058_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _283_ (
    .I0(\regfile[7] [4]),
    .I1(\regfile[3] [4]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_059_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _284_ (
    .I0(\regfile[6] [4]),
    .I1(\regfile[2] [4]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_060_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _285_ (
    .I0(\regfile[14] [4]),
    .I1(\regfile[10] [4]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_061_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _286_ (
    .I0(\regfile[15] [4]),
    .I1(\regfile[11] [4]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_062_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _287_ (
    .I0(_069_),
    .I1(_068_),
    .I2(_064_),
    .I3(rdAddrA[3]),
    .O(_063_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _288_ (
    .I0(_066_),
    .I1(_067_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_064_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _289_ (
    .I0(\regfile[5] [4]),
    .I1(\regfile[1] [4]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_066_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _290_ (
    .I0(\regfile[4] [4]),
    .I1(\regfile[0] [4]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_067_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _291_ (
    .I0(\regfile[12] [4]),
    .I1(\regfile[8] [4]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_068_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _292_ (
    .I0(\regfile[13] [4]),
    .I1(\regfile[9] [4]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_069_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _293_ (
    .I0(_070_),
    .I1(_076_),
    .I2(rdAddrA[1]),
    .I3(1'b0),
    .O(_002_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _294_ (
    .I0(_075_),
    .I1(_074_),
    .I2(_071_),
    .I3(rdAddrA[3]),
    .O(_070_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _295_ (
    .I0(_072_),
    .I1(_073_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_071_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _296_ (
    .I0(\regfile[7] [5]),
    .I1(\regfile[3] [5]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_072_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _297_ (
    .I0(\regfile[6] [5]),
    .I1(\regfile[2] [5]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_073_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _298_ (
    .I0(\regfile[14] [5]),
    .I1(\regfile[10] [5]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_074_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _299_ (
    .I0(\regfile[15] [5]),
    .I1(\regfile[11] [5]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_075_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _300_ (
    .I0(_081_),
    .I1(_080_),
    .I2(_077_),
    .I3(rdAddrA[3]),
    .O(_076_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _301_ (
    .I0(_078_),
    .I1(_079_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_077_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _302_ (
    .I0(\regfile[5] [5]),
    .I1(\regfile[1] [5]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_078_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _303_ (
    .I0(\regfile[4] [5]),
    .I1(\regfile[0] [5]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_079_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _304_ (
    .I0(\regfile[12] [5]),
    .I1(\regfile[8] [5]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_080_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _305_ (
    .I0(\regfile[13] [5]),
    .I1(\regfile[9] [5]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_081_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _306_ (
    .I0(_082_),
    .I1(_088_),
    .I2(rdAddrA[1]),
    .I3(1'b0),
    .O(_003_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _307_ (
    .I0(_087_),
    .I1(_086_),
    .I2(_083_),
    .I3(rdAddrA[3]),
    .O(_082_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _308_ (
    .I0(_084_),
    .I1(_085_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_083_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _309_ (
    .I0(\regfile[7] [6]),
    .I1(\regfile[3] [6]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_084_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _310_ (
    .I0(\regfile[6] [6]),
    .I1(\regfile[2] [6]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_085_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _311_ (
    .I0(\regfile[14] [6]),
    .I1(\regfile[10] [6]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_086_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _312_ (
    .I0(\regfile[15] [6]),
    .I1(\regfile[11] [6]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_087_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _313_ (
    .I0(_093_),
    .I1(_092_),
    .I2(_089_),
    .I3(rdAddrA[3]),
    .O(_088_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _314_ (
    .I0(_090_),
    .I1(_091_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_089_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _315_ (
    .I0(\regfile[5] [6]),
    .I1(\regfile[1] [6]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_090_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _316_ (
    .I0(\regfile[4] [6]),
    .I1(\regfile[0] [6]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_091_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _317_ (
    .I0(\regfile[12] [6]),
    .I1(\regfile[8] [6]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_092_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _318_ (
    .I0(\regfile[13] [6]),
    .I1(\regfile[9] [6]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_093_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _319_ (
    .I0(_095_),
    .I1(_101_),
    .I2(rdAddrA[1]),
    .I3(1'b0),
    .O(_004_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _320_ (
    .I0(_100_),
    .I1(_099_),
    .I2(_096_),
    .I3(rdAddrA[3]),
    .O(_095_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _321_ (
    .I0(_097_),
    .I1(_098_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_096_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _322_ (
    .I0(\regfile[7] [7]),
    .I1(\regfile[3] [7]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_097_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _323_ (
    .I0(\regfile[6] [7]),
    .I1(\regfile[2] [7]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_098_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _324_ (
    .I0(\regfile[14] [7]),
    .I1(\regfile[10] [7]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_099_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _325_ (
    .I0(\regfile[15] [7]),
    .I1(\regfile[11] [7]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_100_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _326_ (
    .I0(_106_),
    .I1(_105_),
    .I2(_102_),
    .I3(rdAddrA[3]),
    .O(_101_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _327_ (
    .I0(_103_),
    .I1(_104_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_102_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _328_ (
    .I0(\regfile[5] [7]),
    .I1(\regfile[1] [7]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_103_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _329_ (
    .I0(\regfile[4] [7]),
    .I1(\regfile[0] [7]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_104_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _330_ (
    .I0(\regfile[12] [7]),
    .I1(\regfile[8] [7]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_105_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _331_ (
    .I0(\regfile[13] [7]),
    .I1(\regfile[9] [7]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_106_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _332_ (
    .I0(_107_),
    .I1(_113_),
    .I2(rdAddrA[3]),
    .I3(1'b0),
    .O(_005_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _333_ (
    .I0(_112_),
    .I1(_111_),
    .I2(_108_),
    .I3(rdAddrA[1]),
    .O(_107_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _334_ (
    .I0(_109_),
    .I1(_110_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_108_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _335_ (
    .I0(\regfile[13] [8]),
    .I1(\regfile[9] [8]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_109_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _336_ (
    .I0(\regfile[12] [8]),
    .I1(\regfile[8] [8]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_110_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _337_ (
    .I0(\regfile[14] [8]),
    .I1(\regfile[10] [8]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_111_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _338_ (
    .I0(\regfile[15] [8]),
    .I1(\regfile[11] [8]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_112_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _339_ (
    .I0(_118_),
    .I1(_117_),
    .I2(_114_),
    .I3(rdAddrA[1]),
    .O(_113_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:43" *)
  SB_LUT4 #(
    .LUT_INIT(4'b0001)
  ) _340_ (
    .I0(_115_),
    .I1(_116_),
    .I2(1'b0),
    .I3(1'b0),
    .O(_114_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _341_ (
    .I0(\regfile[5] [8]),
    .I1(\regfile[1] [8]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_115_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _342_ (
    .I0(\regfile[4] [8]),
    .I1(\regfile[0] [8]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_116_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _343_ (
    .I0(\regfile[6] [8]),
    .I1(\regfile[2] [8]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_117_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _344_ (
    .I0(\regfile[7] [8]),
    .I1(\regfile[3] [8]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_118_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _345_ (
    .I0(_119_),
    .I1(_126_),
    .I2(rdAddrA[3]),
    .I3(1'b0),
    .O(_007_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _346_ (
    .I0(_125_),
    .I1(_124_),
    .I2(_120_),
    .I3(rdAddrA[1]),
    .O(_119_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _347_ (
    .I0(_121_),
    .I1(_123_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_120_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _348_ (
    .I0(\regfile[13] [9]),
    .I1(\regfile[9] [9]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_121_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _349_ (
    .I0(\regfile[12] [9]),
    .I1(\regfile[8] [9]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_123_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _350_ (
    .I0(\regfile[14] [9]),
    .I1(\regfile[10] [9]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_124_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _351_ (
    .I0(\regfile[15] [9]),
    .I1(\regfile[11] [9]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_125_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _352_ (
    .I0(_131_),
    .I1(_130_),
    .I2(_127_),
    .I3(rdAddrA[1]),
    .O(_126_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:43" *)
  SB_LUT4 #(
    .LUT_INIT(4'b0001)
  ) _353_ (
    .I0(_128_),
    .I1(_129_),
    .I2(1'b0),
    .I3(1'b0),
    .O(_127_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _354_ (
    .I0(\regfile[5] [9]),
    .I1(\regfile[1] [9]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_128_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _355_ (
    .I0(\regfile[4] [9]),
    .I1(\regfile[0] [9]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_129_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _356_ (
    .I0(\regfile[6] [9]),
    .I1(\regfile[2] [9]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_130_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _357_ (
    .I0(\regfile[7] [9]),
    .I1(\regfile[3] [9]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_131_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _358_ (
    .I0(_132_),
    .I1(_138_),
    .I2(rdAddrA[1]),
    .I3(1'b0),
    .O(_036_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _359_ (
    .I0(_137_),
    .I1(_136_),
    .I2(_133_),
    .I3(rdAddrA[3]),
    .O(_132_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _360_ (
    .I0(_134_),
    .I1(_135_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_133_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _361_ (
    .I0(\regfile[7] [10]),
    .I1(\regfile[3] [10]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_134_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _362_ (
    .I0(\regfile[6] [10]),
    .I1(\regfile[2] [10]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_135_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _363_ (
    .I0(\regfile[14] [10]),
    .I1(\regfile[10] [10]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_136_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _364_ (
    .I0(\regfile[15] [10]),
    .I1(\regfile[11] [10]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_137_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _365_ (
    .I0(_143_),
    .I1(_142_),
    .I2(_139_),
    .I3(rdAddrA[3]),
    .O(_138_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _366_ (
    .I0(_140_),
    .I1(_141_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_139_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _367_ (
    .I0(\regfile[5] [10]),
    .I1(\regfile[1] [10]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_140_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _368_ (
    .I0(\regfile[4] [10]),
    .I1(\regfile[0] [10]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_141_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _369_ (
    .I0(\regfile[12] [10]),
    .I1(\regfile[8] [10]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_142_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _370_ (
    .I0(\regfile[13] [10]),
    .I1(\regfile[9] [10]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_143_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _371_ (
    .I0(_144_),
    .I1(_150_),
    .I2(rdAddrA[3]),
    .I3(1'b0),
    .O(_065_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _372_ (
    .I0(_149_),
    .I1(_148_),
    .I2(_145_),
    .I3(rdAddrA[1]),
    .O(_144_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _373_ (
    .I0(_146_),
    .I1(_147_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_145_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _374_ (
    .I0(\regfile[13] [11]),
    .I1(\regfile[9] [11]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_146_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _375_ (
    .I0(\regfile[12] [11]),
    .I1(\regfile[8] [11]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_147_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _376_ (
    .I0(\regfile[14] [11]),
    .I1(\regfile[10] [11]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_148_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _377_ (
    .I0(\regfile[15] [11]),
    .I1(\regfile[11] [11]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_149_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _378_ (
    .I0(_156_),
    .I1(_155_),
    .I2(_152_),
    .I3(rdAddrA[1]),
    .O(_150_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:43" *)
  SB_LUT4 #(
    .LUT_INIT(4'b0001)
  ) _379_ (
    .I0(_153_),
    .I1(_154_),
    .I2(1'b0),
    .I3(1'b0),
    .O(_152_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _380_ (
    .I0(\regfile[5] [11]),
    .I1(\regfile[1] [11]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_153_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _381_ (
    .I0(\regfile[4] [11]),
    .I1(\regfile[0] [11]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_154_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _382_ (
    .I0(\regfile[6] [11]),
    .I1(\regfile[2] [11]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_155_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _383_ (
    .I0(\regfile[7] [11]),
    .I1(\regfile[3] [11]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_156_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _384_ (
    .I0(_157_),
    .I1(_163_),
    .I2(rdAddrA[1]),
    .I3(1'b0),
    .O(_094_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _385_ (
    .I0(_162_),
    .I1(_161_),
    .I2(_158_),
    .I3(rdAddrA[3]),
    .O(_157_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _386_ (
    .I0(_159_),
    .I1(_160_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_158_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _387_ (
    .I0(\regfile[7] [12]),
    .I1(\regfile[3] [12]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_159_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _388_ (
    .I0(\regfile[6] [12]),
    .I1(\regfile[2] [12]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_160_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _389_ (
    .I0(\regfile[14] [12]),
    .I1(\regfile[10] [12]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_161_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _390_ (
    .I0(\regfile[15] [12]),
    .I1(\regfile[11] [12]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_162_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _391_ (
    .I0(_168_),
    .I1(_167_),
    .I2(_164_),
    .I3(rdAddrA[3]),
    .O(_163_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _392_ (
    .I0(_165_),
    .I1(_166_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_164_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _393_ (
    .I0(\regfile[5] [12]),
    .I1(\regfile[1] [12]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_165_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _394_ (
    .I0(\regfile[4] [12]),
    .I1(\regfile[0] [12]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_166_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _395_ (
    .I0(\regfile[12] [12]),
    .I1(\regfile[8] [12]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_167_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _396_ (
    .I0(\regfile[13] [12]),
    .I1(\regfile[9] [12]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_168_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _397_ (
    .I0(_169_),
    .I1(_175_),
    .I2(rdAddrA[1]),
    .I3(1'b0),
    .O(_122_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _398_ (
    .I0(_174_),
    .I1(_173_),
    .I2(_170_),
    .I3(rdAddrA[3]),
    .O(_169_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _399_ (
    .I0(_171_),
    .I1(_172_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_170_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _400_ (
    .I0(\regfile[7] [13]),
    .I1(\regfile[3] [13]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_171_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _401_ (
    .I0(\regfile[6] [13]),
    .I1(\regfile[2] [13]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_172_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _402_ (
    .I0(\regfile[14] [13]),
    .I1(\regfile[10] [13]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_173_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _403_ (
    .I0(\regfile[15] [13]),
    .I1(\regfile[11] [13]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_174_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _404_ (
    .I0(_181_),
    .I1(_179_),
    .I2(_176_),
    .I3(rdAddrA[3]),
    .O(_175_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _405_ (
    .I0(_177_),
    .I1(_178_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_176_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _406_ (
    .I0(\regfile[5] [13]),
    .I1(\regfile[1] [13]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_177_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _407_ (
    .I0(\regfile[4] [13]),
    .I1(\regfile[0] [13]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_178_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _408_ (
    .I0(\regfile[12] [13]),
    .I1(\regfile[8] [13]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_179_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _409_ (
    .I0(\regfile[13] [13]),
    .I1(\regfile[9] [13]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_181_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _410_ (
    .I0(_182_),
    .I1(_188_),
    .I2(rdAddrA[3]),
    .I3(1'b0),
    .O(_151_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _411_ (
    .I0(_187_),
    .I1(_186_),
    .I2(_183_),
    .I3(rdAddrA[1]),
    .O(_182_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _412_ (
    .I0(_184_),
    .I1(_185_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_183_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _413_ (
    .I0(\regfile[13] [14]),
    .I1(\regfile[9] [14]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_184_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _414_ (
    .I0(\regfile[12] [14]),
    .I1(\regfile[8] [14]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_185_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _415_ (
    .I0(\regfile[14] [14]),
    .I1(\regfile[10] [14]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_186_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _416_ (
    .I0(\regfile[15] [14]),
    .I1(\regfile[11] [14]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_187_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _417_ (
    .I0(_193_),
    .I1(_192_),
    .I2(_189_),
    .I3(rdAddrA[1]),
    .O(_188_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:43" *)
  SB_LUT4 #(
    .LUT_INIT(4'b0001)
  ) _418_ (
    .I0(_190_),
    .I1(_191_),
    .I2(1'b0),
    .I3(1'b0),
    .O(_189_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _419_ (
    .I0(\regfile[5] [14]),
    .I1(\regfile[1] [14]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_190_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _420_ (
    .I0(\regfile[4] [14]),
    .I1(\regfile[0] [14]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_191_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _421_ (
    .I0(\regfile[6] [14]),
    .I1(\regfile[2] [14]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_192_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _422_ (
    .I0(\regfile[7] [14]),
    .I1(\regfile[3] [14]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_193_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _423_ (
    .I0(_194_),
    .I1(_200_),
    .I2(rdAddrA[3]),
    .I3(1'b0),
    .O(_180_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _424_ (
    .I0(_199_),
    .I1(_198_),
    .I2(_195_),
    .I3(rdAddrA[1]),
    .O(_194_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _425_ (
    .I0(_196_),
    .I1(_197_),
    .I2(rdAddrA[0]),
    .I3(1'b0),
    .O(_195_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _426_ (
    .I0(\regfile[13] [15]),
    .I1(\regfile[9] [15]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_196_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10101100)
  ) _427_ (
    .I0(\regfile[12] [15]),
    .I1(\regfile[8] [15]),
    .I2(rdAddrA[2]),
    .I3(1'b0),
    .O(_197_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _428_ (
    .I0(\regfile[14] [15]),
    .I1(\regfile[10] [15]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_198_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _429_ (
    .I0(\regfile[15] [15]),
    .I1(\regfile[11] [15]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_199_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0001000111110000)
  ) _430_ (
    .I0(_205_),
    .I1(_204_),
    .I2(_201_),
    .I3(rdAddrA[1]),
    .O(_200_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:43" *)
  SB_LUT4 #(
    .LUT_INIT(4'b0001)
  ) _431_ (
    .I0(_202_),
    .I1(_203_),
    .I2(1'b0),
    .I3(1'b0),
    .O(_201_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _432_ (
    .I0(\regfile[5] [15]),
    .I1(\regfile[1] [15]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_202_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _433_ (
    .I0(\regfile[4] [15]),
    .I1(\regfile[0] [15]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_203_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0000010100000011)
  ) _434_ (
    .I0(\regfile[6] [15]),
    .I1(\regfile[2] [15]),
    .I2(rdAddrA[0]),
    .I3(rdAddrA[2]),
    .O(_204_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:51" *)
  SB_LUT4 #(
    .LUT_INIT(16'b0101001100000000)
  ) _435_ (
    .I0(\regfile[7] [15]),
    .I1(\regfile[3] [15]),
    .I2(rdAddrA[2]),
    .I3(rdAddrA[0]),
    .O(_205_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10000000)
  ) _436_ (
    .I0(_206_),
    .I1(wrAddr[2]),
    .I2(wrAddr[3]),
    .I3(1'b0),
    .O(_208_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b00010000)
  ) _437_ (
    .I0(wrAddr[0]),
    .I1(wrAddr[1]),
    .I2(wrEn),
    .I3(1'b0),
    .O(_206_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10000000)
  ) _438_ (
    .I0(_207_),
    .I1(wrAddr[2]),
    .I2(wrAddr[3]),
    .I3(1'b0),
    .O(_211_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b01000000)
  ) _439_ (
    .I0(wrAddr[1]),
    .I1(wrAddr[0]),
    .I2(wrEn),
    .I3(1'b0),
    .O(_207_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10000000)
  ) _440_ (
    .I0(_209_),
    .I1(wrAddr[2]),
    .I2(wrAddr[3]),
    .I3(1'b0),
    .O(_212_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b01000000)
  ) _441_ (
    .I0(wrAddr[0]),
    .I1(wrAddr[1]),
    .I2(wrEn),
    .I3(1'b0),
    .O(_209_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10000000)
  ) _442_ (
    .I0(_210_),
    .I1(wrAddr[2]),
    .I2(wrAddr[3]),
    .I3(1'b0),
    .O(_213_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b10000000)
  ) _443_ (
    .I0(wrAddr[0]),
    .I1(wrAddr[1]),
    .I2(wrEn),
    .I3(1'b0),
    .O(_210_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b00010000)
  ) _444_ (
    .I0(wrAddr[2]),
    .I1(wrAddr[3]),
    .I2(_206_),
    .I3(1'b0),
    .O(_214_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b00010000)
  ) _445_ (
    .I0(wrAddr[2]),
    .I1(wrAddr[3]),
    .I2(_207_),
    .I3(1'b0),
    .O(_215_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b00010000)
  ) _446_ (
    .I0(wrAddr[2]),
    .I1(wrAddr[3]),
    .I2(_209_),
    .I3(1'b0),
    .O(_216_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b00010000)
  ) _447_ (
    .I0(wrAddr[2]),
    .I1(wrAddr[3]),
    .I2(_210_),
    .I3(1'b0),
    .O(_217_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b01000000)
  ) _448_ (
    .I0(wrAddr[3]),
    .I1(wrAddr[2]),
    .I2(_206_),
    .I3(1'b0),
    .O(_218_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b01000000)
  ) _449_ (
    .I0(wrAddr[3]),
    .I1(wrAddr[2]),
    .I2(_207_),
    .I3(1'b0),
    .O(_219_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b01000000)
  ) _450_ (
    .I0(wrAddr[3]),
    .I1(wrAddr[2]),
    .I2(_209_),
    .I3(1'b0),
    .O(_220_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b01000000)
  ) _451_ (
    .I0(wrAddr[3]),
    .I1(wrAddr[2]),
    .I2(_210_),
    .I3(1'b0),
    .O(_221_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b01000000)
  ) _452_ (
    .I0(wrAddr[2]),
    .I1(_206_),
    .I2(wrAddr[3]),
    .I3(1'b0),
    .O(_222_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b01000000)
  ) _453_ (
    .I0(wrAddr[2]),
    .I1(_207_),
    .I2(wrAddr[3]),
    .I3(1'b0),
    .O(_223_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b01000000)
  ) _454_ (
    .I0(wrAddr[2]),
    .I1(_209_),
    .I2(wrAddr[3]),
    .I3(1'b0),
    .O(_224_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:47" *)
  SB_LUT4 #(
    .LUT_INIT(8'b01000000)
  ) _455_ (
    .I0(wrAddr[2]),
    .I1(_210_),
    .I2(wrAddr[3]),
    .I3(1'b0),
    .O(_225_)
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _456_ (
    .C(clk),
    .D(wrData[0]),
    .E(_216_),
    .Q(\regfile[2] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _457_ (
    .C(clk),
    .D(wrData[1]),
    .E(_216_),
    .Q(\regfile[2] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _458_ (
    .C(clk),
    .D(wrData[2]),
    .E(_216_),
    .Q(\regfile[2] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _459_ (
    .C(clk),
    .D(wrData[3]),
    .E(_216_),
    .Q(\regfile[2] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _460_ (
    .C(clk),
    .D(wrData[4]),
    .E(_216_),
    .Q(\regfile[2] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _461_ (
    .C(clk),
    .D(wrData[5]),
    .E(_216_),
    .Q(\regfile[2] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _462_ (
    .C(clk),
    .D(wrData[6]),
    .E(_216_),
    .Q(\regfile[2] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _463_ (
    .C(clk),
    .D(wrData[7]),
    .E(_216_),
    .Q(\regfile[2] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _464_ (
    .C(clk),
    .D(wrData[8]),
    .E(_216_),
    .Q(\regfile[2] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _465_ (
    .C(clk),
    .D(wrData[9]),
    .E(_216_),
    .Q(\regfile[2] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _466_ (
    .C(clk),
    .D(wrData[10]),
    .E(_216_),
    .Q(\regfile[2] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _467_ (
    .C(clk),
    .D(wrData[11]),
    .E(_216_),
    .Q(\regfile[2] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _468_ (
    .C(clk),
    .D(wrData[12]),
    .E(_216_),
    .Q(\regfile[2] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _469_ (
    .C(clk),
    .D(wrData[13]),
    .E(_216_),
    .Q(\regfile[2] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _470_ (
    .C(clk),
    .D(wrData[14]),
    .E(_216_),
    .Q(\regfile[2] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _471_ (
    .C(clk),
    .D(wrData[15]),
    .E(_216_),
    .Q(\regfile[2] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _472_ (
    .C(clk),
    .D(wrData[0]),
    .E(_215_),
    .Q(\regfile[1] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _473_ (
    .C(clk),
    .D(wrData[1]),
    .E(_215_),
    .Q(\regfile[1] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _474_ (
    .C(clk),
    .D(wrData[2]),
    .E(_215_),
    .Q(\regfile[1] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _475_ (
    .C(clk),
    .D(wrData[3]),
    .E(_215_),
    .Q(\regfile[1] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _476_ (
    .C(clk),
    .D(wrData[4]),
    .E(_215_),
    .Q(\regfile[1] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _477_ (
    .C(clk),
    .D(wrData[5]),
    .E(_215_),
    .Q(\regfile[1] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _478_ (
    .C(clk),
    .D(wrData[6]),
    .E(_215_),
    .Q(\regfile[1] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _479_ (
    .C(clk),
    .D(wrData[7]),
    .E(_215_),
    .Q(\regfile[1] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _480_ (
    .C(clk),
    .D(wrData[8]),
    .E(_215_),
    .Q(\regfile[1] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _481_ (
    .C(clk),
    .D(wrData[9]),
    .E(_215_),
    .Q(\regfile[1] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _482_ (
    .C(clk),
    .D(wrData[10]),
    .E(_215_),
    .Q(\regfile[1] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _483_ (
    .C(clk),
    .D(wrData[11]),
    .E(_215_),
    .Q(\regfile[1] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _484_ (
    .C(clk),
    .D(wrData[12]),
    .E(_215_),
    .Q(\regfile[1] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _485_ (
    .C(clk),
    .D(wrData[13]),
    .E(_215_),
    .Q(\regfile[1] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _486_ (
    .C(clk),
    .D(wrData[14]),
    .E(_215_),
    .Q(\regfile[1] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _487_ (
    .C(clk),
    .D(wrData[15]),
    .E(_215_),
    .Q(\regfile[1] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _488_ (
    .C(clk),
    .D(wrData[0]),
    .E(_219_),
    .Q(\regfile[5] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _489_ (
    .C(clk),
    .D(wrData[1]),
    .E(_219_),
    .Q(\regfile[5] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _490_ (
    .C(clk),
    .D(wrData[2]),
    .E(_219_),
    .Q(\regfile[5] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _491_ (
    .C(clk),
    .D(wrData[3]),
    .E(_219_),
    .Q(\regfile[5] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _492_ (
    .C(clk),
    .D(wrData[4]),
    .E(_219_),
    .Q(\regfile[5] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _493_ (
    .C(clk),
    .D(wrData[5]),
    .E(_219_),
    .Q(\regfile[5] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _494_ (
    .C(clk),
    .D(wrData[6]),
    .E(_219_),
    .Q(\regfile[5] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _495_ (
    .C(clk),
    .D(wrData[7]),
    .E(_219_),
    .Q(\regfile[5] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _496_ (
    .C(clk),
    .D(wrData[8]),
    .E(_219_),
    .Q(\regfile[5] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _497_ (
    .C(clk),
    .D(wrData[9]),
    .E(_219_),
    .Q(\regfile[5] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _498_ (
    .C(clk),
    .D(wrData[10]),
    .E(_219_),
    .Q(\regfile[5] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _499_ (
    .C(clk),
    .D(wrData[11]),
    .E(_219_),
    .Q(\regfile[5] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _500_ (
    .C(clk),
    .D(wrData[12]),
    .E(_219_),
    .Q(\regfile[5] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _501_ (
    .C(clk),
    .D(wrData[13]),
    .E(_219_),
    .Q(\regfile[5] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _502_ (
    .C(clk),
    .D(wrData[14]),
    .E(_219_),
    .Q(\regfile[5] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _503_ (
    .C(clk),
    .D(wrData[15]),
    .E(_219_),
    .Q(\regfile[5] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _504_ (
    .C(clk),
    .D(wrData[0]),
    .E(_214_),
    .Q(\regfile[0] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _505_ (
    .C(clk),
    .D(wrData[1]),
    .E(_214_),
    .Q(\regfile[0] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _506_ (
    .C(clk),
    .D(wrData[2]),
    .E(_214_),
    .Q(\regfile[0] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _507_ (
    .C(clk),
    .D(wrData[3]),
    .E(_214_),
    .Q(\regfile[0] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _508_ (
    .C(clk),
    .D(wrData[4]),
    .E(_214_),
    .Q(\regfile[0] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _509_ (
    .C(clk),
    .D(wrData[5]),
    .E(_214_),
    .Q(\regfile[0] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _510_ (
    .C(clk),
    .D(wrData[6]),
    .E(_214_),
    .Q(\regfile[0] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _511_ (
    .C(clk),
    .D(wrData[7]),
    .E(_214_),
    .Q(\regfile[0] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _512_ (
    .C(clk),
    .D(wrData[8]),
    .E(_214_),
    .Q(\regfile[0] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _513_ (
    .C(clk),
    .D(wrData[9]),
    .E(_214_),
    .Q(\regfile[0] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _514_ (
    .C(clk),
    .D(wrData[10]),
    .E(_214_),
    .Q(\regfile[0] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _515_ (
    .C(clk),
    .D(wrData[11]),
    .E(_214_),
    .Q(\regfile[0] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _516_ (
    .C(clk),
    .D(wrData[12]),
    .E(_214_),
    .Q(\regfile[0] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _517_ (
    .C(clk),
    .D(wrData[13]),
    .E(_214_),
    .Q(\regfile[0] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _518_ (
    .C(clk),
    .D(wrData[14]),
    .E(_214_),
    .Q(\regfile[0] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _519_ (
    .C(clk),
    .D(wrData[15]),
    .E(_214_),
    .Q(\regfile[0] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _520_ (
    .C(clk),
    .D(wrData[0]),
    .E(_218_),
    .Q(\regfile[4] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _521_ (
    .C(clk),
    .D(wrData[1]),
    .E(_218_),
    .Q(\regfile[4] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _522_ (
    .C(clk),
    .D(wrData[2]),
    .E(_218_),
    .Q(\regfile[4] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _523_ (
    .C(clk),
    .D(wrData[3]),
    .E(_218_),
    .Q(\regfile[4] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _524_ (
    .C(clk),
    .D(wrData[4]),
    .E(_218_),
    .Q(\regfile[4] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _525_ (
    .C(clk),
    .D(wrData[5]),
    .E(_218_),
    .Q(\regfile[4] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _526_ (
    .C(clk),
    .D(wrData[6]),
    .E(_218_),
    .Q(\regfile[4] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _527_ (
    .C(clk),
    .D(wrData[7]),
    .E(_218_),
    .Q(\regfile[4] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _528_ (
    .C(clk),
    .D(wrData[8]),
    .E(_218_),
    .Q(\regfile[4] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _529_ (
    .C(clk),
    .D(wrData[9]),
    .E(_218_),
    .Q(\regfile[4] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _530_ (
    .C(clk),
    .D(wrData[10]),
    .E(_218_),
    .Q(\regfile[4] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _531_ (
    .C(clk),
    .D(wrData[11]),
    .E(_218_),
    .Q(\regfile[4] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _532_ (
    .C(clk),
    .D(wrData[12]),
    .E(_218_),
    .Q(\regfile[4] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _533_ (
    .C(clk),
    .D(wrData[13]),
    .E(_218_),
    .Q(\regfile[4] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _534_ (
    .C(clk),
    .D(wrData[14]),
    .E(_218_),
    .Q(\regfile[4] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _535_ (
    .C(clk),
    .D(wrData[15]),
    .E(_218_),
    .Q(\regfile[4] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _536_ (
    .C(clk),
    .D(wrData[0]),
    .E(_217_),
    .Q(\regfile[3] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _537_ (
    .C(clk),
    .D(wrData[1]),
    .E(_217_),
    .Q(\regfile[3] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _538_ (
    .C(clk),
    .D(wrData[2]),
    .E(_217_),
    .Q(\regfile[3] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _539_ (
    .C(clk),
    .D(wrData[3]),
    .E(_217_),
    .Q(\regfile[3] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _540_ (
    .C(clk),
    .D(wrData[4]),
    .E(_217_),
    .Q(\regfile[3] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _541_ (
    .C(clk),
    .D(wrData[5]),
    .E(_217_),
    .Q(\regfile[3] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _542_ (
    .C(clk),
    .D(wrData[6]),
    .E(_217_),
    .Q(\regfile[3] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _543_ (
    .C(clk),
    .D(wrData[7]),
    .E(_217_),
    .Q(\regfile[3] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _544_ (
    .C(clk),
    .D(wrData[8]),
    .E(_217_),
    .Q(\regfile[3] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _545_ (
    .C(clk),
    .D(wrData[9]),
    .E(_217_),
    .Q(\regfile[3] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _546_ (
    .C(clk),
    .D(wrData[10]),
    .E(_217_),
    .Q(\regfile[3] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _547_ (
    .C(clk),
    .D(wrData[11]),
    .E(_217_),
    .Q(\regfile[3] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _548_ (
    .C(clk),
    .D(wrData[12]),
    .E(_217_),
    .Q(\regfile[3] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _549_ (
    .C(clk),
    .D(wrData[13]),
    .E(_217_),
    .Q(\regfile[3] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _550_ (
    .C(clk),
    .D(wrData[14]),
    .E(_217_),
    .Q(\regfile[3] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _551_ (
    .C(clk),
    .D(wrData[15]),
    .E(_217_),
    .Q(\regfile[3] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _552_ (
    .C(clk),
    .D(wrData[0]),
    .E(_220_),
    .Q(\regfile[6] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _553_ (
    .C(clk),
    .D(wrData[1]),
    .E(_220_),
    .Q(\regfile[6] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _554_ (
    .C(clk),
    .D(wrData[2]),
    .E(_220_),
    .Q(\regfile[6] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _555_ (
    .C(clk),
    .D(wrData[3]),
    .E(_220_),
    .Q(\regfile[6] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _556_ (
    .C(clk),
    .D(wrData[4]),
    .E(_220_),
    .Q(\regfile[6] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _557_ (
    .C(clk),
    .D(wrData[5]),
    .E(_220_),
    .Q(\regfile[6] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _558_ (
    .C(clk),
    .D(wrData[6]),
    .E(_220_),
    .Q(\regfile[6] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _559_ (
    .C(clk),
    .D(wrData[7]),
    .E(_220_),
    .Q(\regfile[6] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _560_ (
    .C(clk),
    .D(wrData[8]),
    .E(_220_),
    .Q(\regfile[6] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _561_ (
    .C(clk),
    .D(wrData[9]),
    .E(_220_),
    .Q(\regfile[6] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _562_ (
    .C(clk),
    .D(wrData[10]),
    .E(_220_),
    .Q(\regfile[6] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _563_ (
    .C(clk),
    .D(wrData[11]),
    .E(_220_),
    .Q(\regfile[6] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _564_ (
    .C(clk),
    .D(wrData[12]),
    .E(_220_),
    .Q(\regfile[6] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _565_ (
    .C(clk),
    .D(wrData[13]),
    .E(_220_),
    .Q(\regfile[6] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _566_ (
    .C(clk),
    .D(wrData[14]),
    .E(_220_),
    .Q(\regfile[6] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _567_ (
    .C(clk),
    .D(wrData[15]),
    .E(_220_),
    .Q(\regfile[6] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _568_ (
    .C(clk),
    .D(wrData[0]),
    .E(_221_),
    .Q(\regfile[7] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _569_ (
    .C(clk),
    .D(wrData[1]),
    .E(_221_),
    .Q(\regfile[7] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _570_ (
    .C(clk),
    .D(wrData[2]),
    .E(_221_),
    .Q(\regfile[7] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _571_ (
    .C(clk),
    .D(wrData[3]),
    .E(_221_),
    .Q(\regfile[7] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _572_ (
    .C(clk),
    .D(wrData[4]),
    .E(_221_),
    .Q(\regfile[7] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _573_ (
    .C(clk),
    .D(wrData[5]),
    .E(_221_),
    .Q(\regfile[7] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _574_ (
    .C(clk),
    .D(wrData[6]),
    .E(_221_),
    .Q(\regfile[7] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _575_ (
    .C(clk),
    .D(wrData[7]),
    .E(_221_),
    .Q(\regfile[7] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _576_ (
    .C(clk),
    .D(wrData[8]),
    .E(_221_),
    .Q(\regfile[7] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _577_ (
    .C(clk),
    .D(wrData[9]),
    .E(_221_),
    .Q(\regfile[7] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _578_ (
    .C(clk),
    .D(wrData[10]),
    .E(_221_),
    .Q(\regfile[7] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _579_ (
    .C(clk),
    .D(wrData[11]),
    .E(_221_),
    .Q(\regfile[7] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _580_ (
    .C(clk),
    .D(wrData[12]),
    .E(_221_),
    .Q(\regfile[7] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _581_ (
    .C(clk),
    .D(wrData[13]),
    .E(_221_),
    .Q(\regfile[7] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _582_ (
    .C(clk),
    .D(wrData[14]),
    .E(_221_),
    .Q(\regfile[7] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _583_ (
    .C(clk),
    .D(wrData[15]),
    .E(_221_),
    .Q(\regfile[7] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _584_ (
    .C(clk),
    .D(wrData[0]),
    .E(_222_),
    .Q(\regfile[8] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _585_ (
    .C(clk),
    .D(wrData[1]),
    .E(_222_),
    .Q(\regfile[8] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _586_ (
    .C(clk),
    .D(wrData[2]),
    .E(_222_),
    .Q(\regfile[8] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _587_ (
    .C(clk),
    .D(wrData[3]),
    .E(_222_),
    .Q(\regfile[8] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _588_ (
    .C(clk),
    .D(wrData[4]),
    .E(_222_),
    .Q(\regfile[8] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _589_ (
    .C(clk),
    .D(wrData[5]),
    .E(_222_),
    .Q(\regfile[8] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _590_ (
    .C(clk),
    .D(wrData[6]),
    .E(_222_),
    .Q(\regfile[8] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _591_ (
    .C(clk),
    .D(wrData[7]),
    .E(_222_),
    .Q(\regfile[8] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _592_ (
    .C(clk),
    .D(wrData[8]),
    .E(_222_),
    .Q(\regfile[8] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _593_ (
    .C(clk),
    .D(wrData[9]),
    .E(_222_),
    .Q(\regfile[8] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _594_ (
    .C(clk),
    .D(wrData[10]),
    .E(_222_),
    .Q(\regfile[8] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _595_ (
    .C(clk),
    .D(wrData[11]),
    .E(_222_),
    .Q(\regfile[8] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _596_ (
    .C(clk),
    .D(wrData[12]),
    .E(_222_),
    .Q(\regfile[8] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _597_ (
    .C(clk),
    .D(wrData[13]),
    .E(_222_),
    .Q(\regfile[8] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _598_ (
    .C(clk),
    .D(wrData[14]),
    .E(_222_),
    .Q(\regfile[8] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _599_ (
    .C(clk),
    .D(wrData[15]),
    .E(_222_),
    .Q(\regfile[8] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _600_ (
    .C(clk),
    .D(wrData[0]),
    .E(_223_),
    .Q(\regfile[9] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _601_ (
    .C(clk),
    .D(wrData[1]),
    .E(_223_),
    .Q(\regfile[9] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _602_ (
    .C(clk),
    .D(wrData[2]),
    .E(_223_),
    .Q(\regfile[9] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _603_ (
    .C(clk),
    .D(wrData[3]),
    .E(_223_),
    .Q(\regfile[9] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _604_ (
    .C(clk),
    .D(wrData[4]),
    .E(_223_),
    .Q(\regfile[9] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _605_ (
    .C(clk),
    .D(wrData[5]),
    .E(_223_),
    .Q(\regfile[9] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _606_ (
    .C(clk),
    .D(wrData[6]),
    .E(_223_),
    .Q(\regfile[9] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _607_ (
    .C(clk),
    .D(wrData[7]),
    .E(_223_),
    .Q(\regfile[9] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _608_ (
    .C(clk),
    .D(wrData[8]),
    .E(_223_),
    .Q(\regfile[9] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _609_ (
    .C(clk),
    .D(wrData[9]),
    .E(_223_),
    .Q(\regfile[9] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _610_ (
    .C(clk),
    .D(wrData[10]),
    .E(_223_),
    .Q(\regfile[9] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _611_ (
    .C(clk),
    .D(wrData[11]),
    .E(_223_),
    .Q(\regfile[9] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _612_ (
    .C(clk),
    .D(wrData[12]),
    .E(_223_),
    .Q(\regfile[9] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _613_ (
    .C(clk),
    .D(wrData[13]),
    .E(_223_),
    .Q(\regfile[9] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _614_ (
    .C(clk),
    .D(wrData[14]),
    .E(_223_),
    .Q(\regfile[9] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _615_ (
    .C(clk),
    .D(wrData[15]),
    .E(_223_),
    .Q(\regfile[9] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _616_ (
    .C(clk),
    .D(wrData[0]),
    .E(_224_),
    .Q(\regfile[10] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _617_ (
    .C(clk),
    .D(wrData[1]),
    .E(_224_),
    .Q(\regfile[10] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _618_ (
    .C(clk),
    .D(wrData[2]),
    .E(_224_),
    .Q(\regfile[10] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _619_ (
    .C(clk),
    .D(wrData[3]),
    .E(_224_),
    .Q(\regfile[10] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _620_ (
    .C(clk),
    .D(wrData[4]),
    .E(_224_),
    .Q(\regfile[10] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _621_ (
    .C(clk),
    .D(wrData[5]),
    .E(_224_),
    .Q(\regfile[10] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _622_ (
    .C(clk),
    .D(wrData[6]),
    .E(_224_),
    .Q(\regfile[10] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _623_ (
    .C(clk),
    .D(wrData[7]),
    .E(_224_),
    .Q(\regfile[10] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _624_ (
    .C(clk),
    .D(wrData[8]),
    .E(_224_),
    .Q(\regfile[10] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _625_ (
    .C(clk),
    .D(wrData[9]),
    .E(_224_),
    .Q(\regfile[10] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _626_ (
    .C(clk),
    .D(wrData[10]),
    .E(_224_),
    .Q(\regfile[10] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _627_ (
    .C(clk),
    .D(wrData[11]),
    .E(_224_),
    .Q(\regfile[10] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _628_ (
    .C(clk),
    .D(wrData[12]),
    .E(_224_),
    .Q(\regfile[10] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _629_ (
    .C(clk),
    .D(wrData[13]),
    .E(_224_),
    .Q(\regfile[10] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _630_ (
    .C(clk),
    .D(wrData[14]),
    .E(_224_),
    .Q(\regfile[10] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _631_ (
    .C(clk),
    .D(wrData[15]),
    .E(_224_),
    .Q(\regfile[10] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _632_ (
    .C(clk),
    .D(wrData[0]),
    .E(_225_),
    .Q(\regfile[11] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _633_ (
    .C(clk),
    .D(wrData[1]),
    .E(_225_),
    .Q(\regfile[11] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _634_ (
    .C(clk),
    .D(wrData[2]),
    .E(_225_),
    .Q(\regfile[11] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _635_ (
    .C(clk),
    .D(wrData[3]),
    .E(_225_),
    .Q(\regfile[11] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _636_ (
    .C(clk),
    .D(wrData[4]),
    .E(_225_),
    .Q(\regfile[11] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _637_ (
    .C(clk),
    .D(wrData[5]),
    .E(_225_),
    .Q(\regfile[11] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _638_ (
    .C(clk),
    .D(wrData[6]),
    .E(_225_),
    .Q(\regfile[11] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _639_ (
    .C(clk),
    .D(wrData[7]),
    .E(_225_),
    .Q(\regfile[11] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _640_ (
    .C(clk),
    .D(wrData[8]),
    .E(_225_),
    .Q(\regfile[11] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _641_ (
    .C(clk),
    .D(wrData[9]),
    .E(_225_),
    .Q(\regfile[11] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _642_ (
    .C(clk),
    .D(wrData[10]),
    .E(_225_),
    .Q(\regfile[11] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _643_ (
    .C(clk),
    .D(wrData[11]),
    .E(_225_),
    .Q(\regfile[11] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _644_ (
    .C(clk),
    .D(wrData[12]),
    .E(_225_),
    .Q(\regfile[11] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _645_ (
    .C(clk),
    .D(wrData[13]),
    .E(_225_),
    .Q(\regfile[11] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _646_ (
    .C(clk),
    .D(wrData[14]),
    .E(_225_),
    .Q(\regfile[11] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _647_ (
    .C(clk),
    .D(wrData[15]),
    .E(_225_),
    .Q(\regfile[11] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _648_ (
    .C(clk),
    .D(wrData[0]),
    .E(_208_),
    .Q(\regfile[12] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _649_ (
    .C(clk),
    .D(wrData[1]),
    .E(_208_),
    .Q(\regfile[12] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _650_ (
    .C(clk),
    .D(wrData[2]),
    .E(_208_),
    .Q(\regfile[12] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _651_ (
    .C(clk),
    .D(wrData[3]),
    .E(_208_),
    .Q(\regfile[12] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _652_ (
    .C(clk),
    .D(wrData[4]),
    .E(_208_),
    .Q(\regfile[12] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _653_ (
    .C(clk),
    .D(wrData[5]),
    .E(_208_),
    .Q(\regfile[12] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _654_ (
    .C(clk),
    .D(wrData[6]),
    .E(_208_),
    .Q(\regfile[12] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _655_ (
    .C(clk),
    .D(wrData[7]),
    .E(_208_),
    .Q(\regfile[12] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _656_ (
    .C(clk),
    .D(wrData[8]),
    .E(_208_),
    .Q(\regfile[12] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _657_ (
    .C(clk),
    .D(wrData[9]),
    .E(_208_),
    .Q(\regfile[12] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _658_ (
    .C(clk),
    .D(wrData[10]),
    .E(_208_),
    .Q(\regfile[12] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _659_ (
    .C(clk),
    .D(wrData[11]),
    .E(_208_),
    .Q(\regfile[12] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _660_ (
    .C(clk),
    .D(wrData[12]),
    .E(_208_),
    .Q(\regfile[12] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _661_ (
    .C(clk),
    .D(wrData[13]),
    .E(_208_),
    .Q(\regfile[12] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _662_ (
    .C(clk),
    .D(wrData[14]),
    .E(_208_),
    .Q(\regfile[12] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _663_ (
    .C(clk),
    .D(wrData[15]),
    .E(_208_),
    .Q(\regfile[12] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _664_ (
    .C(clk),
    .D(wrData[0]),
    .E(_211_),
    .Q(\regfile[13] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _665_ (
    .C(clk),
    .D(wrData[1]),
    .E(_211_),
    .Q(\regfile[13] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _666_ (
    .C(clk),
    .D(wrData[2]),
    .E(_211_),
    .Q(\regfile[13] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _667_ (
    .C(clk),
    .D(wrData[3]),
    .E(_211_),
    .Q(\regfile[13] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _668_ (
    .C(clk),
    .D(wrData[4]),
    .E(_211_),
    .Q(\regfile[13] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _669_ (
    .C(clk),
    .D(wrData[5]),
    .E(_211_),
    .Q(\regfile[13] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _670_ (
    .C(clk),
    .D(wrData[6]),
    .E(_211_),
    .Q(\regfile[13] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _671_ (
    .C(clk),
    .D(wrData[7]),
    .E(_211_),
    .Q(\regfile[13] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _672_ (
    .C(clk),
    .D(wrData[8]),
    .E(_211_),
    .Q(\regfile[13] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _673_ (
    .C(clk),
    .D(wrData[9]),
    .E(_211_),
    .Q(\regfile[13] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _674_ (
    .C(clk),
    .D(wrData[10]),
    .E(_211_),
    .Q(\regfile[13] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _675_ (
    .C(clk),
    .D(wrData[11]),
    .E(_211_),
    .Q(\regfile[13] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _676_ (
    .C(clk),
    .D(wrData[12]),
    .E(_211_),
    .Q(\regfile[13] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _677_ (
    .C(clk),
    .D(wrData[13]),
    .E(_211_),
    .Q(\regfile[13] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _678_ (
    .C(clk),
    .D(wrData[14]),
    .E(_211_),
    .Q(\regfile[13] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _679_ (
    .C(clk),
    .D(wrData[15]),
    .E(_211_),
    .Q(\regfile[13] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _680_ (
    .C(clk),
    .D(wrData[0]),
    .E(_212_),
    .Q(\regfile[14] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _681_ (
    .C(clk),
    .D(wrData[1]),
    .E(_212_),
    .Q(\regfile[14] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _682_ (
    .C(clk),
    .D(wrData[2]),
    .E(_212_),
    .Q(\regfile[14] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _683_ (
    .C(clk),
    .D(wrData[3]),
    .E(_212_),
    .Q(\regfile[14] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _684_ (
    .C(clk),
    .D(wrData[4]),
    .E(_212_),
    .Q(\regfile[14] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _685_ (
    .C(clk),
    .D(wrData[5]),
    .E(_212_),
    .Q(\regfile[14] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _686_ (
    .C(clk),
    .D(wrData[6]),
    .E(_212_),
    .Q(\regfile[14] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _687_ (
    .C(clk),
    .D(wrData[7]),
    .E(_212_),
    .Q(\regfile[14] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _688_ (
    .C(clk),
    .D(wrData[8]),
    .E(_212_),
    .Q(\regfile[14] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _689_ (
    .C(clk),
    .D(wrData[9]),
    .E(_212_),
    .Q(\regfile[14] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _690_ (
    .C(clk),
    .D(wrData[10]),
    .E(_212_),
    .Q(\regfile[14] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _691_ (
    .C(clk),
    .D(wrData[11]),
    .E(_212_),
    .Q(\regfile[14] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _692_ (
    .C(clk),
    .D(wrData[12]),
    .E(_212_),
    .Q(\regfile[14] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _693_ (
    .C(clk),
    .D(wrData[13]),
    .E(_212_),
    .Q(\regfile[14] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _694_ (
    .C(clk),
    .D(wrData[14]),
    .E(_212_),
    .Q(\regfile[14] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _695_ (
    .C(clk),
    .D(wrData[15]),
    .E(_212_),
    .Q(\regfile[14] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _696_ (
    .C(clk),
    .D(wrData[0]),
    .E(_213_),
    .Q(\regfile[15] [0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _697_ (
    .C(clk),
    .D(wrData[1]),
    .E(_213_),
    .Q(\regfile[15] [1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _698_ (
    .C(clk),
    .D(wrData[2]),
    .E(_213_),
    .Q(\regfile[15] [2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _699_ (
    .C(clk),
    .D(wrData[3]),
    .E(_213_),
    .Q(\regfile[15] [3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _700_ (
    .C(clk),
    .D(wrData[4]),
    .E(_213_),
    .Q(\regfile[15] [4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _701_ (
    .C(clk),
    .D(wrData[5]),
    .E(_213_),
    .Q(\regfile[15] [5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _702_ (
    .C(clk),
    .D(wrData[6]),
    .E(_213_),
    .Q(\regfile[15] [6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _703_ (
    .C(clk),
    .D(wrData[7]),
    .E(_213_),
    .Q(\regfile[15] [7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _704_ (
    .C(clk),
    .D(wrData[8]),
    .E(_213_),
    .Q(\regfile[15] [8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _705_ (
    .C(clk),
    .D(wrData[9]),
    .E(_213_),
    .Q(\regfile[15] [9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _706_ (
    .C(clk),
    .D(wrData[10]),
    .E(_213_),
    .Q(\regfile[15] [10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _707_ (
    .C(clk),
    .D(wrData[11]),
    .E(_213_),
    .Q(\regfile[15] [11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _708_ (
    .C(clk),
    .D(wrData[12]),
    .E(_213_),
    .Q(\regfile[15] [12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _709_ (
    .C(clk),
    .D(wrData[13]),
    .E(_213_),
    .Q(\regfile[15] [13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _710_ (
    .C(clk),
    .D(wrData[14]),
    .E(_213_),
    .Q(\regfile[15] [14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _711_ (
    .C(clk),
    .D(wrData[15]),
    .E(_213_),
    .Q(\regfile[15] [15])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _712_ (
    .C(clk),
    .D(_006_),
    .Q(rdDataA[0])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _713_ (
    .C(clk),
    .D(_226_),
    .Q(rdDataA[1])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _714_ (
    .C(clk),
    .D(_227_),
    .Q(rdDataA[2])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _715_ (
    .C(clk),
    .D(_000_),
    .Q(rdDataA[3])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _716_ (
    .C(clk),
    .D(_001_),
    .Q(rdDataA[4])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _717_ (
    .C(clk),
    .D(_002_),
    .Q(rdDataA[5])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _718_ (
    .C(clk),
    .D(_003_),
    .Q(rdDataA[6])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _719_ (
    .C(clk),
    .D(_004_),
    .Q(rdDataA[7])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _720_ (
    .C(clk),
    .D(_005_),
    .Q(rdDataA[8])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _721_ (
    .C(clk),
    .D(_007_),
    .Q(rdDataA[9])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _722_ (
    .C(clk),
    .D(_036_),
    .Q(rdDataA[10])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _723_ (
    .C(clk),
    .D(_065_),
    .Q(rdDataA[11])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _724_ (
    .C(clk),
    .D(_094_),
    .Q(rdDataA[12])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _725_ (
    .C(clk),
    .D(_122_),
    .Q(rdDataA[13])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _726_ (
    .C(clk),
    .D(_151_),
    .Q(rdDataA[14])
  );
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _727_ (
    .C(clk),
    .D(_180_),
    .Q(rdDataA[15])
  );
endmodule
