/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "ibuffer.v:3" *)
module ibuffer(clk, ldata, rdata, lvalid, lrdy, rvalid, rrdy);
  (* src = "ibuffer.v:35" *)
  wire [7:0] _000_;
  (* src = "ibuffer.v:35" *)
  wire [7:0] _001_;
  (* src = "ibuffer.v:35" *)
  wire [7:0] _002_;
  (* src = "ibuffer.v:35" *)
  wire [7:0] _003_;
  (* src = "ibuffer.v:35" *)
  wire [7:0] _004_;
  (* src = "ibuffer.v:35" *)
  wire [2:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  (* src = "ibuffer.v:4" *)
  input clk;
  (* src = "ibuffer.v:3" *)
  reg [7:0] \fifo[0] ;
  (* src = "ibuffer.v:3" *)
  reg [7:0] \fifo[1] ;
  (* src = "ibuffer.v:3" *)
  reg [7:0] \fifo[2] ;
  (* src = "ibuffer.v:3" *)
  reg [7:0] \fifo[3] ;
  (* src = "ibuffer.v:17" *)
  reg [7:0] irdata;
  (* src = "ibuffer.v:8" *)
  input [7:0] ldata;
  (* src = "ibuffer.v:7" *)
  output lrdy;
  (* src = "ibuffer.v:6" *)
  input lvalid;
  (* init = 3'b011 *)
  (* src = "ibuffer.v:19" *)
  reg [2:0] pnt;
  initial pnt = 3'b011;
  (* src = "ibuffer.v:12" *)
  output [7:0] rdata;
  (* src = "ibuffer.v:10" *)
  input rrdy;
  (* src = "ibuffer.v:11" *)
  output rvalid;
  assign _139_ = _009_ ? _090_ : _024_;
  assign _140_ = ~((_139_ | _019_) & (lrdy | _138_));
  assign _141_ = _088_ ? \fifo[1] [0] : _140_;
  assign _001_[0] = rvalid ? _141_ : _137_;
  assign _142_ = _016_ ? ldata[1] : \fifo[1] [1];
  assign _143_ = _009_ ? \fifo[1] [1] : _142_;
  assign _144_ = ~\fifo[0] [1];
  assign _145_ = _009_ ? _096_ : _032_;
  assign _146_ = ~((_145_ | _019_) & (lrdy | _144_));
  assign _147_ = _088_ ? \fifo[1] [1] : _146_;
  assign _001_[1] = rvalid ? _147_ : _143_;
  assign _148_ = _016_ ? ldata[2] : \fifo[1] [2];
  assign _149_ = _009_ ? \fifo[1] [2] : _148_;
  assign _150_ = ~\fifo[0] [2];
  assign _151_ = _009_ ? _102_ : _040_;
  assign _152_ = ~((_151_ | _019_) & (lrdy | _150_));
  assign _153_ = _088_ ? \fifo[1] [2] : _152_;
  assign _001_[2] = rvalid ? _153_ : _149_;
  assign _154_ = _016_ ? ldata[3] : \fifo[1] [3];
  assign _155_ = _009_ ? \fifo[1] [3] : _154_;
  assign _156_ = ~\fifo[0] [3];
  assign _157_ = _009_ ? _108_ : _048_;
  assign _158_ = ~((_157_ | _019_) & (lrdy | _156_));
  assign _159_ = _088_ ? \fifo[1] [3] : _158_;
  assign _001_[3] = rvalid ? _159_ : _155_;
  assign _160_ = _016_ ? ldata[4] : \fifo[1] [4];
  assign _161_ = _009_ ? \fifo[1] [4] : _160_;
  assign _162_ = ~\fifo[0] [4];
  assign _163_ = _009_ ? _114_ : _056_;
  assign _164_ = ~((_163_ | _019_) & (lrdy | _162_));
  assign _165_ = _088_ ? \fifo[1] [4] : _164_;
  assign _001_[4] = rvalid ? _165_ : _161_;
  assign _166_ = _016_ ? ldata[5] : \fifo[1] [5];
  assign _167_ = _009_ ? \fifo[1] [5] : _166_;
  assign _168_ = ~\fifo[0] [5];
  assign _169_ = _009_ ? _120_ : _064_;
  assign _170_ = ~((_169_ | _019_) & (lrdy | _168_));
  assign _171_ = _088_ ? \fifo[1] [5] : _170_;
  assign _001_[5] = rvalid ? _171_ : _167_;
  assign _172_ = _016_ ? ldata[6] : \fifo[1] [6];
  assign _173_ = _009_ ? \fifo[1] [6] : _172_;
  assign _174_ = ~\fifo[0] [6];
  assign _175_ = _009_ ? _126_ : _072_;
  assign _176_ = ~((_175_ | _019_) & (lrdy | _174_));
  assign _177_ = _088_ ? \fifo[1] [6] : _176_;
  assign _001_[6] = rvalid ? _177_ : _173_;
  assign _178_ = _016_ ? ldata[7] : \fifo[1] [7];
  assign _179_ = _009_ ? \fifo[1] [7] : _178_;
  assign _180_ = ~\fifo[0] [7];
  assign _181_ = _009_ ? _132_ : _080_;
  assign _182_ = ~((_181_ | _019_) & (lrdy | _180_));
  assign _183_ = _088_ ? \fifo[1] [7] : _182_;
  assign _001_[7] = rvalid ? _183_ : _179_;
  assign _184_ = _009_ ^ pnt[0];
  assign _185_ = ~(_009_ | pnt[0]);
  assign _186_ = _185_ | _019_;
  assign _187_ = _185_ | _014_;
  assign _188_ = ~_006_;
  assign _189_ = _016_ & _223_;
  assign _190_ = ~(_009_ | _012_);
  assign _191_ = ~((_190_ & _189_) | (_188_ & _223_));
  assign _192_ = _191_ & _187_;
  assign _193_ = _192_ & _186_;
  assign _194_ = ~((pnt[1] & pnt[0]) | _223_);
  assign _195_ = _194_ | _008_;
  assign _005_[0] = ~((_195_ | _193_) & (_184_ | rvalid));
  assign _196_ = _018_ | _188_;
  assign _197_ = _009_ ? pnt[1] : _196_;
  assign _198_ = ~(_009_ | pnt[1]);
  assign _199_ = _009_ | _015_;
  assign _200_ = ~((_199_ & _085_) | _014_);
  assign _201_ = ~((_199_ | _019_) & _007_);
  assign _202_ = ~(_201_ | _200_);
  assign _203_ = ~((_198_ | _017_) & _202_);
  assign _204_ = _203_ | _194_;
  assign _005_[1] = rvalid ? _204_ : _197_;
  assign _205_ = _018_ ^ pnt[2];
  assign _206_ = _009_ ? pnt[2] : _205_;
  assign _005_[2] = rvalid ? _194_ : _206_;
  assign _004_[0] = rvalid ? \fifo[3] [0] : irdata[0];
  assign _004_[1] = rvalid ? \fifo[3] [1] : irdata[1];
  assign _004_[2] = rvalid ? \fifo[3] [2] : irdata[2];
  assign _004_[3] = rvalid ? \fifo[3] [3] : irdata[3];
  assign _004_[4] = rvalid ? \fifo[3] [4] : irdata[4];
  assign _004_[5] = rvalid ? \fifo[3] [5] : irdata[5];
  assign _004_[6] = rvalid ? \fifo[3] [6] : irdata[6];
  assign _004_[7] = rvalid ? \fifo[3] [7] : irdata[7];
  assign _207_ = _018_ ? ldata[0] : \fifo[0] [0];
  assign _208_ = _009_ ? \fifo[0] [0] : _207_;
  assign _000_[0] = rvalid ? \fifo[0] [0] : _208_;
  assign _209_ = _018_ ? ldata[1] : \fifo[0] [1];
  assign _210_ = _009_ ? \fifo[0] [1] : _209_;
  assign _000_[1] = rvalid ? \fifo[0] [1] : _210_;
  assign _211_ = _018_ ? ldata[2] : \fifo[0] [2];
  assign _212_ = _009_ ? \fifo[0] [2] : _211_;
  assign _000_[2] = rvalid ? \fifo[0] [2] : _212_;
  assign _213_ = _018_ ? ldata[3] : \fifo[0] [3];
  assign _214_ = _009_ ? \fifo[0] [3] : _213_;
  assign _000_[3] = rvalid ? \fifo[0] [3] : _214_;
  assign _215_ = _018_ ? ldata[4] : \fifo[0] [4];
  assign _216_ = _009_ ? \fifo[0] [4] : _215_;
  assign _000_[4] = rvalid ? \fifo[0] [4] : _216_;
  assign _217_ = _018_ ? ldata[5] : \fifo[0] [5];
  assign _218_ = _009_ ? \fifo[0] [5] : _217_;
  assign _000_[5] = rvalid ? \fifo[0] [5] : _218_;
  assign _219_ = _018_ ? ldata[6] : \fifo[0] [6];
  assign _220_ = _009_ ? \fifo[0] [6] : _219_;
  assign _000_[6] = rvalid ? \fifo[0] [6] : _220_;
  assign _221_ = _018_ ? ldata[7] : \fifo[0] [7];
  assign _222_ = _009_ ? \fifo[0] [7] : _221_;
  assign _000_[7] = rvalid ? \fifo[0] [7] : _222_;
  assign _223_ = ~pnt[2];
  assign _006_ = ~(pnt[1] & pnt[0]);
  assign lrdy = _006_ | _223_;
  assign _007_ = _006_ | pnt[2];
  assign rvalid = _007_ & rrdy;
  assign _008_ = ~rvalid;
  assign _009_ = ~((_006_ | _223_) & lvalid);
  assign _010_ = _006_ ? \fifo[3] [0] : ldata[0];
  assign _011_ = _009_ ? \fifo[3] [0] : _010_;
  assign _012_ = ~pnt[0];
  assign _013_ = pnt[1] & _012_;
  assign _014_ = ~(_013_ & _223_);
  assign _015_ = ~pnt[1];
  assign _016_ = _015_ & pnt[0];
  assign _017_ = ~(_016_ & _223_);
  assign _018_ = ~(pnt[1] | pnt[0]);
  assign _019_ = ~(_018_ & _223_);
  assign _020_ = _019_ & _017_;
  assign _021_ = _020_ & lrdy;
  assign _022_ = _021_ & _014_;
  assign _023_ = ~\fifo[2] [0];
  assign _024_ = ~ldata[0];
  assign _025_ = ~\fifo[3] [0];
  assign _026_ = _009_ ? _025_ : _024_;
  assign _027_ = ~((_026_ | _014_) & (_021_ | _023_));
  assign _028_ = _022_ ? \fifo[3] [0] : _027_;
  assign _003_[0] = rvalid ? _028_ : _011_;
  assign _029_ = _006_ ? \fifo[3] [1] : ldata[1];
  assign _030_ = _009_ ? \fifo[3] [1] : _029_;
  assign _031_ = ~\fifo[2] [1];
  assign _032_ = ~ldata[1];
  assign _033_ = ~\fifo[3] [1];
  assign _034_ = _009_ ? _033_ : _032_;
  assign _035_ = ~((_034_ | _014_) & (_021_ | _031_));
  assign _036_ = _022_ ? \fifo[3] [1] : _035_;
  assign _003_[1] = rvalid ? _036_ : _030_;
  assign _037_ = _006_ ? \fifo[3] [2] : ldata[2];
  assign _038_ = _009_ ? \fifo[3] [2] : _037_;
  assign _039_ = ~\fifo[2] [2];
  assign _040_ = ~ldata[2];
  assign _041_ = ~\fifo[3] [2];
  assign _042_ = _009_ ? _041_ : _040_;
  assign _043_ = ~((_042_ | _014_) & (_021_ | _039_));
  assign _044_ = _022_ ? \fifo[3] [2] : _043_;
  assign _003_[2] = rvalid ? _044_ : _038_;
  assign _045_ = _006_ ? \fifo[3] [3] : ldata[3];
  assign _046_ = _009_ ? \fifo[3] [3] : _045_;
  assign _047_ = ~\fifo[2] [3];
  assign _048_ = ~ldata[3];
  assign _049_ = ~\fifo[3] [3];
  assign _050_ = _009_ ? _049_ : _048_;
  assign _051_ = ~((_050_ | _014_) & (_021_ | _047_));
  assign _052_ = _022_ ? \fifo[3] [3] : _051_;
  assign _003_[3] = rvalid ? _052_ : _046_;
  assign _053_ = _006_ ? \fifo[3] [4] : ldata[4];
  assign _054_ = _009_ ? \fifo[3] [4] : _053_;
  assign _055_ = ~\fifo[2] [4];
  assign _056_ = ~ldata[4];
  assign _057_ = ~\fifo[3] [4];
  assign _058_ = _009_ ? _057_ : _056_;
  assign _059_ = ~((_058_ | _014_) & (_021_ | _055_));
  assign _060_ = _022_ ? \fifo[3] [4] : _059_;
  assign _003_[4] = rvalid ? _060_ : _054_;
  assign _061_ = _006_ ? \fifo[3] [5] : ldata[5];
  assign _062_ = _009_ ? \fifo[3] [5] : _061_;
  assign _063_ = ~\fifo[2] [5];
  assign _064_ = ~ldata[5];
  assign _065_ = ~\fifo[3] [5];
  assign _066_ = _009_ ? _065_ : _064_;
  assign _067_ = ~((_066_ | _014_) & (_021_ | _063_));
  assign _068_ = _022_ ? \fifo[3] [5] : _067_;
  assign _003_[5] = rvalid ? _068_ : _062_;
  assign _069_ = _006_ ? \fifo[3] [6] : ldata[6];
  assign _070_ = _009_ ? \fifo[3] [6] : _069_;
  assign _071_ = ~\fifo[2] [6];
  assign _072_ = ~ldata[6];
  assign _073_ = ~\fifo[3] [6];
  assign _074_ = _009_ ? _073_ : _072_;
  assign _075_ = ~((_074_ | _014_) & (_021_ | _071_));
  assign _076_ = _022_ ? \fifo[3] [6] : _075_;
  assign _003_[6] = rvalid ? _076_ : _070_;
  assign _077_ = _006_ ? \fifo[3] [7] : ldata[7];
  assign _078_ = _009_ ? \fifo[3] [7] : _077_;
  assign _079_ = ~\fifo[2] [7];
  assign _080_ = ~ldata[7];
  assign _081_ = ~\fifo[3] [7];
  assign _082_ = _009_ ? _081_ : _080_;
  assign _083_ = ~((_082_ | _014_) & (_021_ | _079_));
  assign _084_ = _022_ ? \fifo[3] [7] : _083_;
  assign _003_[7] = rvalid ? _084_ : _078_;
  assign _085_ = ~_009_;
  assign _086_ = _013_ ? ldata[0] : \fifo[2] [0];
  assign _087_ = _009_ ? \fifo[2] [0] : _086_;
  assign _088_ = _019_ & lrdy;
  assign _089_ = _088_ & _017_;
  assign _090_ = ~\fifo[1] [0];
  assign _091_ = _009_ ? _023_ : _024_;
  assign _092_ = ~((_091_ | _017_) & (_088_ | _090_));
  assign _093_ = _089_ ? \fifo[2] [0] : _092_;
  assign _002_[0] = rvalid ? _093_ : _087_;
  assign _094_ = _013_ ? ldata[1] : \fifo[2] [1];
  assign _095_ = _009_ ? \fifo[2] [1] : _094_;
  assign _096_ = ~\fifo[1] [1];
  assign _097_ = _009_ ? _031_ : _032_;
  assign _098_ = ~((_097_ | _017_) & (_088_ | _096_));
  assign _099_ = _089_ ? \fifo[2] [1] : _098_;
  assign _002_[1] = rvalid ? _099_ : _095_;
  assign _100_ = _013_ ? ldata[2] : \fifo[2] [2];
  assign _101_ = _009_ ? \fifo[2] [2] : _100_;
  assign _102_ = ~\fifo[1] [2];
  assign _103_ = _009_ ? _039_ : _040_;
  assign _104_ = ~((_103_ | _017_) & (_088_ | _102_));
  assign _105_ = _089_ ? \fifo[2] [2] : _104_;
  assign _002_[2] = rvalid ? _105_ : _101_;
  assign _106_ = _013_ ? ldata[3] : \fifo[2] [3];
  assign _107_ = _009_ ? \fifo[2] [3] : _106_;
  assign _108_ = ~\fifo[1] [3];
  assign _109_ = _009_ ? _047_ : _048_;
  assign _110_ = ~((_109_ | _017_) & (_088_ | _108_));
  assign _111_ = _089_ ? \fifo[2] [3] : _110_;
  assign _002_[3] = rvalid ? _111_ : _107_;
  assign _112_ = _013_ ? ldata[4] : \fifo[2] [4];
  assign _113_ = _009_ ? \fifo[2] [4] : _112_;
  assign _114_ = ~\fifo[1] [4];
  assign _115_ = _009_ ? _055_ : _056_;
  assign _116_ = ~((_115_ | _017_) & (_088_ | _114_));
  assign _117_ = _089_ ? \fifo[2] [4] : _116_;
  assign _002_[4] = rvalid ? _117_ : _113_;
  assign _118_ = _013_ ? ldata[5] : \fifo[2] [5];
  assign _119_ = _009_ ? \fifo[2] [5] : _118_;
  assign _120_ = ~\fifo[1] [5];
  assign _121_ = _009_ ? _063_ : _064_;
  assign _122_ = ~((_121_ | _017_) & (_088_ | _120_));
  assign _123_ = _089_ ? \fifo[2] [5] : _122_;
  assign _002_[5] = rvalid ? _123_ : _119_;
  assign _124_ = _013_ ? ldata[6] : \fifo[2] [6];
  assign _125_ = _009_ ? \fifo[2] [6] : _124_;
  assign _126_ = ~\fifo[1] [6];
  assign _127_ = _009_ ? _071_ : _072_;
  assign _128_ = ~((_127_ | _017_) & (_088_ | _126_));
  assign _129_ = _089_ ? \fifo[2] [6] : _128_;
  assign _002_[6] = rvalid ? _129_ : _125_;
  assign _130_ = _013_ ? ldata[7] : \fifo[2] [7];
  assign _131_ = _009_ ? \fifo[2] [7] : _130_;
  assign _132_ = ~\fifo[1] [7];
  assign _133_ = _009_ ? _079_ : _080_;
  assign _134_ = ~((_133_ | _017_) & (_088_ | _132_));
  assign _135_ = _089_ ? \fifo[2] [7] : _134_;
  assign _002_[7] = rvalid ? _135_ : _131_;
  assign _136_ = _016_ ? ldata[0] : \fifo[1] [0];
  assign _137_ = _009_ ? \fifo[1] [0] : _136_;
  assign _138_ = ~\fifo[0] [0];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      irdata[0] <= _004_[0];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      irdata[1] <= _004_[1];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      irdata[2] <= _004_[2];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      irdata[3] <= _004_[3];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      irdata[4] <= _004_[4];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      irdata[5] <= _004_[5];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      irdata[6] <= _004_[6];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      irdata[7] <= _004_[7];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      pnt[0] <= _005_[0];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      pnt[1] <= _005_[1];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      pnt[2] <= _005_[2];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[0] [0] <= _000_[0];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[0] [1] <= _000_[1];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[0] [2] <= _000_[2];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[0] [3] <= _000_[3];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[0] [4] <= _000_[4];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[0] [5] <= _000_[5];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[0] [6] <= _000_[6];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[0] [7] <= _000_[7];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[1] [0] <= _001_[0];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[1] [1] <= _001_[1];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[1] [2] <= _001_[2];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[1] [3] <= _001_[3];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[1] [4] <= _001_[4];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[1] [5] <= _001_[5];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[1] [6] <= _001_[6];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[1] [7] <= _001_[7];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[2] [0] <= _002_[0];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[2] [1] <= _002_[1];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[2] [2] <= _002_[2];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[2] [3] <= _002_[3];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[2] [4] <= _002_[4];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[2] [5] <= _002_[5];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[2] [6] <= _002_[6];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[2] [7] <= _002_[7];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[3] [0] <= _003_[0];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[3] [1] <= _003_[1];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[3] [2] <= _003_[2];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[3] [3] <= _003_[3];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[3] [4] <= _003_[4];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[3] [5] <= _003_[5];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[3] [6] <= _003_[6];
  (* src = "ibuffer.v:35" *)
  always @(posedge clk)
      \fifo[3] [7] <= _003_[7];
  assign rdata = irdata;
endmodule
