echo + read_blif _tmp_yosys-abc-jZV61F/input.blif;
read_blif _tmp_yosys-abc-jZV61F/input.blif;
echo + read_lib -w /home/jantsch/developments/Verilog-Projects/AIMS-Book-Examples/Liberty/gscl45nm.lib;
read_lib -w /home/jantsch/developments/Verilog-Projects/AIMS-Book-Examples/Liberty/gscl45nm.lib;
echo + read_constr -v /home/jantsch/developments/Verilog-Projects/AIMS-Book-Examples/ETC/abc-constraints.txt;
read_constr -v /home/jantsch/developments/Verilog-Projects/AIMS-Book-Examples/ETC/abc-constraints.txt;
echo + source /home/jantsch/developments/Verilog-Projects/AIMS-Book-Examples/Scripts/synthscript.abc;
source /home/jantsch/developments/Verilog-Projects/AIMS-Book-Examples/Scripts/synthscript.abc;
echo + write_blif _tmp_yosys-abc-jZV61F/output.blif;
write_blif _tmp_yosys-abc-jZV61F/output.blif
