

# Common setups for all Makefiles like variables for target directories:
include ../ETC/setup.mk

# Set chapter:
chapter := 04-ModelingLatchesDelays

# Use the template for for leafe directories:
include $(MkBase)/IntermediateTemplate.mk

# Specific, local Makefile:
include MakefileComp


