/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "multiplier-Pipelined-h.v:1" *)
module multiplier(a, b, y, clk);
  wire [3:0] _000_;
  wire [5:0] _001_;
  (* src = "multiplier-Pipelined-h.v:31" *)
  wire [7:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  (* src = "multiplier-Pipelined-h.v:4" *)
  input [3:0] a;
  (* src = "multiplier-Pipelined-h.v:9" *)
  wire [3:0] areg;
  (* src = "multiplier-Pipelined-h.v:4" *)
  input [3:0] b;
  (* src = "multiplier-Pipelined-h.v:9" *)
  reg [3:0] breg;
  (* src = "multiplier-Pipelined-h.v:7" *)
  input clk;
  (* src = "multiplier-Pipelined-h.v:1" *)
  wire [7:0] \partials[1] ;
  (* src = "multiplier-Pipelined-h.v:1" *)
  reg [7:0] \partials[3] ;
  (* src = "multiplier-Pipelined-h.v:1" *)
  wire [7:0] \preg[1] ;
  (* src = "multiplier-Pipelined-h.v:1" *)
  wire [7:0] \preg[3] ;
  (* src = "multiplier-Pipelined-h.v:5" *)
  output [7:0] y;
  assign _000_[0] = a[0] & b[0];
  assign _003_ = b[1] & a[0];
  assign _004_ = a[1] & b[0];
  assign _001_[1] = _004_ ^ _003_;
  assign _005_ = b[2] & a[0];
  assign _006_ = a[1] & b[1];
  assign _007_ = _006_ ^ _005_;
  assign _008_ = _004_ & _003_;
  assign _001_[2] = _008_ ^ _007_;
  assign _009_ = b[3] & a[0];
  assign _010_ = a[1] & b[2];
  assign _011_ = _010_ ^ _009_;
  assign _012_ = _006_ & _005_;
  assign _013_ = _008_ & _007_;
  assign _014_ = _013_ | _012_;
  assign _001_[3] = _014_ ^ _011_;
  assign _015_ = a[1] & b[3];
  assign _016_ = _013_ & _011_;
  assign _017_ = _010_ & _009_;
  assign _018_ = _012_ & _011_;
  assign _019_ = _018_ | _017_;
  assign _020_ = _019_ | _016_;
  assign _001_[4] = _020_ ^ _015_;
  assign _001_[5] = _020_ & _015_;
  assign _021_ = breg[0] & areg[2];
  assign _002_[2] = _021_ ^ \partials[1] [2];
  assign _022_ = breg[1] & areg[2];
  assign _023_ = _022_ ^ \partials[1] [3];
  assign _024_ = areg[3] & breg[0];
  assign _025_ = _024_ ^ _023_;
  assign _026_ = _021_ & \partials[1] [2];
  assign _002_[3] = _026_ ^ _025_;
  assign _027_ = areg[2] & breg[2];
  assign _028_ = _027_ ^ \partials[1] [4];
  assign _029_ = breg[1] & areg[3];
  assign _030_ = ~(_029_ ^ _028_);
  assign _031_ = _022_ & \partials[1] [3];
  assign _032_ = ~((_024_ & _023_) | _031_);
  assign _033_ = _032_ ^ _030_;
  assign _034_ = _026_ & _025_;
  assign _002_[4] = _034_ ^ _033_;
  assign _035_ = breg[3] & areg[2];
  assign _036_ = _035_ ^ \partials[1] [5];
  assign _037_ = areg[3] & breg[2];
  assign _038_ = ~(_037_ ^ _036_);
  assign _039_ = _027_ & \partials[1] [4];
  assign _040_ = ~((_029_ & _028_) | _039_);
  assign _041_ = ~(_040_ ^ _038_);
  assign _042_ = _032_ | _030_;
  assign _043_ = ~(_034_ & _033_);
  assign _044_ = _043_ & _042_;
  assign _002_[5] = _044_ ^ _041_;
  assign _045_ = ~(areg[3] & breg[3]);
  assign _046_ = _035_ & \partials[1] [5];
  assign _047_ = ~((_037_ & _036_) | _046_);
  assign _048_ = ~(_047_ ^ _045_);
  assign _049_ = _040_ ^ _038_;
  assign _050_ = _034_ & _033_;
  assign _051_ = _040_ | _038_;
  assign _052_ = ~((_042_ | _041_) & _051_);
  assign _053_ = ~((_050_ & _049_) | _052_);
  assign _002_[6] = _053_ ^ _048_;
  assign _054_ = _047_ | _045_;
  assign _002_[7] = ~((_053_ | _048_) & _054_);
  reg \areg_reg[2] ;
  (* src = "multiplier-Pipelined-h.v:19" *)
  always @(posedge clk)
      \areg_reg[2]  <= a[2];
  assign areg[2] = \areg_reg[2] ;
  reg \areg_reg[3] ;
  (* src = "multiplier-Pipelined-h.v:19" *)
  always @(posedge clk)
      \areg_reg[3]  <= a[3];
  assign areg[3] = \areg_reg[3] ;
  (* src = "multiplier-Pipelined-h.v:19" *)
  always @(posedge clk)
      breg[0] <= b[0];
  (* src = "multiplier-Pipelined-h.v:19" *)
  always @(posedge clk)
      breg[1] <= b[1];
  (* src = "multiplier-Pipelined-h.v:19" *)
  always @(posedge clk)
      breg[2] <= b[2];
  (* src = "multiplier-Pipelined-h.v:19" *)
  always @(posedge clk)
      breg[3] <= b[3];
  reg \partials_reg[1][0] ;
  (* src = "multiplier-Pipelined-h.v:19" *)
  always @(posedge clk)
      \partials_reg[1][0]  <= _000_[0];
  assign \partials[1] [0] = \partials_reg[1][0] ;
  reg \partials_reg[1][1] ;
  (* src = "multiplier-Pipelined-h.v:19" *)
  always @(posedge clk)
      \partials_reg[1][1]  <= _001_[1];
  assign \partials[1] [1] = \partials_reg[1][1] ;
  reg \partials_reg[1][2] ;
  (* src = "multiplier-Pipelined-h.v:19" *)
  always @(posedge clk)
      \partials_reg[1][2]  <= _001_[2];
  assign \partials[1] [2] = \partials_reg[1][2] ;
  reg \partials_reg[1][3] ;
  (* src = "multiplier-Pipelined-h.v:19" *)
  always @(posedge clk)
      \partials_reg[1][3]  <= _001_[3];
  assign \partials[1] [3] = \partials_reg[1][3] ;
  reg \partials_reg[1][4] ;
  (* src = "multiplier-Pipelined-h.v:19" *)
  always @(posedge clk)
      \partials_reg[1][4]  <= _001_[4];
  assign \partials[1] [4] = \partials_reg[1][4] ;
  reg \partials_reg[1][5] ;
  (* src = "multiplier-Pipelined-h.v:19" *)
  always @(posedge clk)
      \partials_reg[1][5]  <= _001_[5];
  assign \partials[1] [5] = \partials_reg[1][5] ;
  (* src = "multiplier-Pipelined-h.v:31" *)
  always @(posedge clk)
      \partials[3] [0] <= \partials[1] [0];
  (* src = "multiplier-Pipelined-h.v:31" *)
  always @(posedge clk)
      \partials[3] [1] <= \partials[1] [1];
  (* src = "multiplier-Pipelined-h.v:31" *)
  always @(posedge clk)
      \partials[3] [2] <= _002_[2];
  (* src = "multiplier-Pipelined-h.v:31" *)
  always @(posedge clk)
      \partials[3] [3] <= _002_[3];
  (* src = "multiplier-Pipelined-h.v:31" *)
  always @(posedge clk)
      \partials[3] [4] <= _002_[4];
  (* src = "multiplier-Pipelined-h.v:31" *)
  always @(posedge clk)
      \partials[3] [5] <= _002_[5];
  (* src = "multiplier-Pipelined-h.v:31" *)
  always @(posedge clk)
      \partials[3] [6] <= _002_[6];
  (* src = "multiplier-Pipelined-h.v:31" *)
  always @(posedge clk)
      \partials[3] [7] <= _002_[7];
  assign \partials[1] [7:6] = 2'b00;
  assign \preg[1]  = { 2'b00, \partials[1] [5:0] };
  assign \preg[3]  = \partials[3] ;
  assign y = \partials[3] ;
endmodule
